[package]
name = "log_lammps_reader"
version = "0.4.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "log_lammps_reader"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.102"
polars = { version = "0.53.0", features = ["lazy"] }
pyo3 = "0.27.2"
pyo3-polars = "0.26.0"
rayon = "1.11.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
