name: Release

on:
  # push:
  #   tags:
  #     - '*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download wheels for Linux x86_64
        uses: actions/download-artifact@v4
        with:
          name: wheels-linux-x86_64
          path: dist
      - name: Download wheels for Linux x86
        uses: actions/download-artifact@v4
        with:
          name: wheels-linux-x86
          path: dist
      - name: Download wheels for Linux aarch64
        uses: actions/download-artifact@v4
        with:
          name: wheels-linux-aarch64
          path: dist
      - name: Download wheels for Linux armv7
        uses: actions/download-artifact@v4
        with:
          name: wheels-linux-armv7
          path: dist
      - name: Download wheels for Linux ppc64le
        uses: actions/download-artifact@v4
        with:
          name: wheels-linux-ppc64le
          path: dist
      - name: Download wheels for musllinux x86_64
        uses: actions/download-artifact@v4
        with:
          name: wheels-musllinux-x86_64
          path: dist
      - name: Download wheels for musllinux x86
        uses: actions/download-artifact@v4
        with:
          name: wheels-musllinux-x86
          path: dist
      - name: Download wheels for musllinux aarch64
        uses: actions/download-artifact@v4
        with:
          name: wheels-musllinux-aarch64
          path: dist
      - name: Download wheels for musllinux armv7
        uses: actions/download-artifact@v4
        with:
          name: wheels-musllinux-armv7
          path: dist
      - name: Download wheels for Windows x64
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-x64
          path: dist
      - name: Download wheels for Windows x86
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-x86
          path: dist
      - name: Download wheels for macOS x86_64
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-x86_64
          path: dist
      - name: Download wheels for macOS aarch64
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-aarch64
          path: dist
      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: wheels-sdist
          path: dist
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --non-interactive --skip-existing dist/*
